[package]
name = "bilikara"
version = "0.7.2"
description = "Bilikara Tauri MVP"
authors = ["VZRXS"]
edition = "2024"
rust-version = "1.88"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri-plugin-dialog = "2"
tauri-plugin-clipboard-manager = "2"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "=0.6.4"
objc2-web-kit = { version = "=0.3.2", default-features = false, features = ["std", "WKWebViewConfiguration"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
