import { readSourceText as readFileSync } from './frontend_contract_support.mjs';
// Existing frontend checks transferred to node:test; no Python execution.
import assert from 'node:assert/strict';
import { test } from 'node:test';
import { existsSync, statSync, globSync } from 'node:fs';
import path from 'node:path';
import { root, runNative } from './desktop_construction_support.mjs';
const ROOT = root;
import { contains, hasContent, sourceIndex, firstMatch, iterableValues, concatenate, subtract, readUniqueJson } from './frontend_contract_support.mjs';
async function checked(program, args, cwd) { const result = await runNative(program, args, process.env, 120000, cwd); assert.equal(result.status, 0, result.stdout + result.stderr); return result; }
const PresentationStaticInvariantsTest = {
async test_display_identifier_preferences_follow_host_without_inline_scripts() {
(await checked("node", ["tests/display_identifier_preferences.cjs"], ROOT));
},
async setUpClass() {
this.static = path.join(ROOT, "static");
this.app = readFileSync(path.join(this.static, "app.js"), "utf8");
this.controller = readFileSync(path.join(this.static, "controller.js"), "utf8");
this.scene = readFileSync(path.join(this.static, "presentation-scene.js"), "utf8");
this.renderer = readFileSync(path.join(this.static, "presentation-renderer.js"), "utf8");
this.sync = readFileSync(path.join(this.static, "presentation-sync.js"), "utf8");
this.index = readFileSync(path.join(this.static, "index.html"), "utf8");
},
async test_rejected_stage_player_and_native_commands_are_removed() {
let combined, entryPath, rejected, relative, tauri_sources;
for (const relative of iterableValues(["static/stage.html", "static/stage.js", "static/stage-sync.js", "static/stage-renderer.js", "static/stage.css", "src-tauri/capabilities/stage.json", "src-tauri/permissions/autogenerated/open_stage_window.toml", "src-tauri/permissions/autogenerated/close_stage_window.toml", "src-tauri/permissions/autogenerated/get_stage_display_info.toml"])) {
assert.ok(!hasContent(existsSync(path.join(ROOT, relative))), relative);
}
tauri_sources = Array.from(Array.from(iterableValues(Array.from(globSync(path.join(path.join(path.join(ROOT, "src-tauri"), "src"), "*.rs"))).sort((a, b) => typeof a === "number" ? a - b : a < b ? -1 : a > b ? 1 : 0)))).map((entryPath) => readFileSync(entryPath, "utf8")).join(`
`);
combined = concatenate(this.app, tauri_sources);
for (const rejected of iterableValues(["open_stage_window", "close_stage_window", "get_stage_display_info"])) {
assert.ok(!contains(rejected, combined));
}
for (const rejected of iterableValues(["renderPlayerDelayItemRow", "renderLocalAdvanceDelayQueue", "delayOverlayItemSignature", "localAdvanceOverlayMode"])) {
assert.ok(!contains(rejected, this.app));
}
},
async test_presentation_modules_load_before_host_and_keep_host_authoritative() {
let app_index, forbidden, presentation_only, renderer_index, scene_index, sync_index;
scene_index = sourceIndex(this.index, "src=\"/presentation-scene.js\"");
renderer_index = sourceIndex(this.index, "src=\"/presentation-renderer.js\"");
sync_index = sourceIndex(this.index, "src=\"/presentation-sync.js\"");
app_index = sourceIndex(this.index, "src=\"/app.js\"");
assert.ok(scene_index < renderer_index);
assert.ok(renderer_index < sync_index);
assert.ok(sync_index < app_index);
presentation_only = [this.scene, this.renderer, this.controller, this.sync].join(`
`);
for (const forbidden of iterableValues(["createElement(\"audio\")", "/api/player/", "EventSource"])) {
assert.ok(!contains(forbidden, presentation_only));
}
assert.ok(contains("createElement(\"video\")", this.controller));
assert.ok(contains("video.muted = true", this.controller));
assert.ok(contains("BroadcastChannel", presentation_only));
assert.ok(!contains("invoke(\"send_presentation_command\"", this.controller));
},
async test_host_publishes_scene_clock_without_constructing_second_media_owner() {
let block, end, forbidden, start;
start = sourceIndex(this.app, "function presentationSceneApi");
end = sourceIndex(this.app, "function renderPlayerFullscreenButton", start);
block = this.app.slice(start, end);
for (const forbidden of iterableValues(["createElement(\"video\")", "createElement(\"audio\")", "open_stage_window"])) {
assert.ok(!contains(forbidden, block));
}
assert.ok(contains("BroadcastChannel", block));
assert.ok(contains("localStorage.setItem", block));
assert.ok(contains("makeEnvelope(\"master-state\"", block));
assert.ok(contains("playbackAuthority !== \"host\"", block));
assert.ok(contains("mediaRendererOwner !== \"host\"", block));
},
async test_i18n_has_controller_and_presentation_keys_in_all_languages() {
let catalog, key, keys, language, language_key_sets, reference_keys, reference_language, rejected, required, result, translations, value;

catalog = readUniqueJson(path.join(this.static, "i18n.json"));
required = new Set(["controller.outputLabel", "controller.connecting", "controller.unavailable", "controller.staleWindow", "controller.controls", "controller.seek", "player.nextSong", "player.volumeTag", "player.fullscreenRemoteExit", "player.fullscreenExit", "display.presentationActive", "display.presentationActivating", "display.presentationRecovering", "display.presentationNoExternalDisplay", "display.presentationDisconnected", "display.outputPanelDescription", "display.hostTargetTitle", "display.hostTargetDescription", "display.presentationSelectHostDisplay", "display.builtInDisplay", "display.hostDestination", "display.hostWillMoveTo", "display.defaultSuffix", "display.identifyDisplays", "display.identificationFailed", "display.identifierCurrentHost", "display.identifierAudience", "display.identifierUnavailable", "controller.play", "controller.pause", "controller.backFifteen", "controller.forwardFifteen", "controller.tauriRequired", "controller.autoplayBlocked", "controller.outputVideoFailed"]);
for (const [language, translations] of iterableValues(Object.entries(catalog["languages"]))) {
assert.deepEqual(subtract(required, new Set((Symbol.iterator in Object(translations) ? translations : Object.keys(translations)))), new Set(), language);
}
rejected = new Set(["display.stageOutput", "display.stageOutputOff", "display.stageOutputConnecting", "display.stageOutputConnected", "display.stageOutputDetected", "display.stageOutputConnectedSecondary", "display.openStage", "display.closeStage", "display.stageOpenFailed", "display.stageTargetSelected", "display.stageDisconnected", "display.stageOutputWindowed", "display.stageOutputConnectedWindowed", "display.windowMode", "display.windowModeDetail", "display.stageWindowSelected", "display.windowOutputOn", "display.stageFellBackWindow", "display.wirelessCast", "display.wirelessCastLater", "display.comingSoon"]);
for (const [language, translations] of iterableValues(Object.entries(catalog["languages"]))) {
assert.deepEqual(new Set(Array.from(rejected).filter(value => contains(value, new Set((Symbol.iterator in Object(translations) ? translations : Object.keys(translations)))))), new Set(), language);
}
language_key_sets = Object.fromEntries(Array.from(Array.from(iterableValues(Object.entries(catalog["languages"])))).map(([language, translations]) => [language, new Set((Symbol.iterator in Object(translations) ? translations : Object.keys(translations)))]));
[reference_language, reference_keys] = firstMatch(Object.entries(language_key_sets));
for (const [language, keys] of iterableValues(Object.entries(language_key_sets))) {
assert.deepEqual(keys, reference_keys, (String(language) + " differs from " + String(reference_language)));
}
},
async test_controller_and_presentation_assets_are_in_the_generic_static_bundle() {
let asset, assets, bundle_source, server_source, static_handler;
assets = ["controller.html", "controller.js", "controller.css", "presentation-scene.js", "presentation-renderer.js", "presentation-sync.js", "display-identifier.html", "display-identifier.js", "display-identifier.css"];
for (const asset of iterableValues(assets)) {
assert.ok(hasContent((existsSync(path.join(this.static, asset)) && statSync(path.join(this.static, asset)).isFile())), asset);
}
assert.ok(!hasContent(existsSync(path.join(this.static, "stage.html"))));
server_source = readFileSync(path.join(path.join(ROOT, "bilikara"), "server.py"), "utf8");
static_handler = server_source.slice(sourceIndex(server_source, "    def _serve_static"), sourceIndex(server_source, "    def _serve_media", sourceIndex(server_source, "    def _serve_static")));
assert.ok(contains("relative = route.lstrip", static_handler));
assert.ok(contains("not static_path.exists()", static_handler));
bundle_source = readFileSync(path.join(path.join(path.join(ROOT, "xtask"), "src"), "files.rs"), "utf8");
assert.ok(contains("let assets = resources.join(\"static\")", bundle_source));
assert.ok(contains("let source_static = config.root.join(\"static\")", bundle_source));
assert.ok(contains("copy(&entry.path(), &assets.join(entry.file_name()))?", bundle_source));
}
};
test("PresentationStaticInvariantsTest.test_display_identifier_preferences_follow_host_without_inline_scripts", async () => { const instance = Object.create(PresentationStaticInvariantsTest); await instance.setUpClass(); await instance.test_display_identifier_preferences_follow_host_without_inline_scripts(); });
test("PresentationStaticInvariantsTest.test_rejected_stage_player_and_native_commands_are_removed", async () => { const instance = Object.create(PresentationStaticInvariantsTest); await instance.setUpClass(); await instance.test_rejected_stage_player_and_native_commands_are_removed(); });
test("PresentationStaticInvariantsTest.test_presentation_modules_load_before_host_and_keep_host_authoritative", async () => { const instance = Object.create(PresentationStaticInvariantsTest); await instance.setUpClass(); await instance.test_presentation_modules_load_before_host_and_keep_host_authoritative(); });
test("PresentationStaticInvariantsTest.test_host_publishes_scene_clock_without_constructing_second_media_owner", async () => { const instance = Object.create(PresentationStaticInvariantsTest); await instance.setUpClass(); await instance.test_host_publishes_scene_clock_without_constructing_second_media_owner(); });
test("PresentationStaticInvariantsTest.test_i18n_has_controller_and_presentation_keys_in_all_languages", async () => { const instance = Object.create(PresentationStaticInvariantsTest); await instance.setUpClass(); await instance.test_i18n_has_controller_and_presentation_keys_in_all_languages(); });
test("PresentationStaticInvariantsTest.test_controller_and_presentation_assets_are_in_the_generic_static_bundle", async () => { const instance = Object.create(PresentationStaticInvariantsTest); await instance.setUpClass(); await instance.test_controller_and_presentation_assets_are_in_the_generic_static_bundle(); });
