from __future__ import annotations

import json
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class PresentationStaticInvariantsTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.static = ROOT / "static"
        cls.app = (cls.static / "app.js").read_text(encoding="utf-8")
        cls.controller = (cls.static / "controller.js").read_text(encoding="utf-8")
        cls.scene = (cls.static / "presentation-scene.js").read_text(encoding="utf-8")
        cls.renderer = (cls.static / "presentation-renderer.js").read_text(encoding="utf-8")
        cls.sync = (cls.static / "presentation-sync.js").read_text(encoding="utf-8")
        cls.index = (cls.static / "index.html").read_text(encoding="utf-8")

    def test_rejected_stage_player_and_native_commands_are_removed(self):
        for relative in (
            "static/stage.html",
            "static/stage.js",
            "static/stage-sync.js",
            "static/stage-renderer.js",
            "static/stage.css",
            "src-tauri/capabilities/stage.json",
            "src-tauri/permissions/autogenerated/open_stage_window.toml",
            "src-tauri/permissions/autogenerated/close_stage_window.toml",
            "src-tauri/permissions/autogenerated/get_stage_display_info.toml",
        ):
            self.assertFalse((ROOT / relative).exists(), relative)
        tauri_sources = "\n".join(
            path.read_text(encoding="utf-8")
            for path in sorted((ROOT / "src-tauri" / "src").glob("*.rs"))
        )
        combined = self.app + tauri_sources
        for rejected in ("open_stage_window", "close_stage_window", "get_stage_display_info"):
            self.assertNotIn(rejected, combined)
        for rejected in (
            "renderPlayerDelayItemRow",
            "renderLocalAdvanceDelayQueue",
            "delayOverlayItemSignature",
            "localAdvanceOverlayMode",
        ):
            self.assertNotIn(rejected, self.app)

    def test_presentation_modules_load_before_host_and_keep_host_authoritative(self):
        scene_index = self.index.index('src="/presentation-scene.js"')
        renderer_index = self.index.index('src="/presentation-renderer.js"')
        sync_index = self.index.index('src="/presentation-sync.js"')
        app_index = self.index.index('src="/app.js"')
        self.assertLess(scene_index, renderer_index)
        self.assertLess(renderer_index, sync_index)
        self.assertLess(sync_index, app_index)
        presentation_only = "\n".join((self.scene, self.renderer, self.controller, self.sync))
        for forbidden in (
            'createElement("audio")',
            "/api/player/",
            "EventSource",
        ):
            self.assertNotIn(forbidden, presentation_only)
        self.assertIn('createElement("video")', self.controller)
        self.assertIn("video.muted = true", self.controller)
        self.assertIn("BroadcastChannel", presentation_only)
        self.assertNotIn('invoke("send_presentation_command"', self.controller)

    def test_host_publishes_scene_clock_without_constructing_second_media_owner(self):
        start = self.app.index("function presentationSceneApi")
        end = self.app.index("function renderPlayerFullscreenButton", start)
        block = self.app[start:end]
        for forbidden in (
            'createElement("video")',
            'createElement("audio")',
            "open_stage_window",
        ):
            self.assertNotIn(forbidden, block)
        self.assertIn("BroadcastChannel", block)
        self.assertIn("localStorage.setItem", block)
        self.assertIn('makeEnvelope("master-state"', block)
        self.assertIn('playbackAuthority !== "host"', block)
        self.assertIn('mediaRendererOwner !== "host"', block)

    def test_i18n_has_controller_and_presentation_keys_in_all_languages(self):
        def reject_duplicate_keys(pairs):
            result = {}
            for key, value in pairs:
                if key in result:
                    raise ValueError(f"duplicate i18n key: {key}")
                result[key] = value
            return result

        catalog = json.loads(
            (self.static / "i18n.json").read_text(encoding="utf-8"),
            object_pairs_hook=reject_duplicate_keys,
        )
        required = {
            "document.controllerTitle",
            "display.presentationActive",
            "display.presentationActivating",
            "display.presentationRecovering",
            "display.presentationNoExternalDisplay",
            "display.presentationDisconnected",
            "display.presentationActiveShort",
            "display.hostTargetTitle",
            "display.hostTargetConfirmHint",
            "display.builtInDisplay",
            "display.hostDestination",
            "controller.title",
            "controller.statusActive",
            "controller.play",
            "controller.pause",
            "controller.backFifteen",
            "controller.forwardFifteen",
            "controller.next",
            "controller.volume",
            "controller.exit",
            "controller.tauriRequired",
            "controller.autoplayBlocked",
            "controller.outputVideoFailed",
        }
        for language, translations in catalog["languages"].items():
            self.assertEqual(required - set(translations), set(), language)
        rejected = {
            "display.stageOutput",
            "display.stageOutputOff",
            "display.stageOutputConnecting",
            "display.stageOutputConnected",
            "display.stageOutputDetected",
            "display.stageOutputConnectedSecondary",
            "display.openStage",
            "display.closeStage",
            "display.stageOpenFailed",
            "display.stageTargetSelected",
            "display.stageDisconnected",
            "display.stageOutputWindowed",
            "display.stageOutputConnectedWindowed",
            "display.windowMode",
            "display.windowModeDetail",
            "display.stageWindowSelected",
            "display.windowOutputOn",
            "display.stageFellBackWindow",
            "display.wirelessCast",
            "display.wirelessCastLater",
            "display.comingSoon",
        }
        for language, translations in catalog["languages"].items():
            self.assertEqual(rejected & set(translations), set(), language)
        language_key_sets = {
            language: set(translations)
            for language, translations in catalog["languages"].items()
        }
        reference_language, reference_keys = next(iter(language_key_sets.items()))
        for language, keys in language_key_sets.items():
            self.assertEqual(keys, reference_keys, f"{language} differs from {reference_language}")

    def test_controller_and_presentation_assets_are_in_the_generic_static_bundle(self):
        assets = (
            "controller.html",
            "controller.js",
            "controller.css",
            "presentation-scene.js",
            "presentation-renderer.js",
            "presentation-sync.js",
        )
        for asset in assets:
            self.assertTrue((self.static / asset).is_file(), asset)
        self.assertFalse((self.static / "stage.html").exists())
        server_source = (ROOT / "bilikara" / "server.py").read_text(encoding="utf-8")
        static_handler = server_source[
            server_source.index("    def _serve_static") : server_source.index(
                "    def _serve_media", server_source.index("    def _serve_static")
            )
        ]
        self.assertIn("relative = route.lstrip", static_handler)
        self.assertIn("not static_path.exists()", static_handler)
        bundle_source = (ROOT / "build_bundle.py").read_text(encoding="utf-8")
        self.assertIn("static_arg =", bundle_source)
        self.assertIn("ROOT_DIR / 'static'", bundle_source)


if __name__ == "__main__":
    unittest.main()
