from __future__ import annotations

import json
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class PresentationStaticInvariantsTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.static = ROOT / "static"
        cls.app = (cls.static / "app.js").read_text(encoding="utf-8")
        cls.controller = (cls.static / "controller.js").read_text(encoding="utf-8")
        cls.scene = (cls.static / "presentation-scene.js").read_text(encoding="utf-8")
        cls.renderer = (cls.static / "presentation-renderer.js").read_text(encoding="utf-8")
        cls.index = (cls.static / "index.html").read_text(encoding="utf-8")

    def test_rejected_stage_player_and_native_commands_are_removed(self):
        for relative in (
            "static/stage.html",
            "static/stage.js",
            "static/stage-sync.js",
            "static/stage-renderer.js",
            "static/stage.css",
            "src-tauri/capabilities/stage.json",
            "src-tauri/permissions/autogenerated/open_stage_window.toml",
            "src-tauri/permissions/autogenerated/close_stage_window.toml",
            "src-tauri/permissions/autogenerated/get_stage_display_info.toml",
        ):
            self.assertFalse((ROOT / relative).exists(), relative)
        combined = self.app + (ROOT / "src-tauri" / "src" / "main.rs").read_text(
            encoding="utf-8"
        )
        for rejected in ("open_stage_window", "close_stage_window", "get_stage_display_info"):
            self.assertNotIn(rejected, combined)
        for rejected in (
            "renderPlayerDelayItemRow",
            "renderLocalAdvanceDelayQueue",
            "delayOverlayItemSignature",
            "localAdvanceOverlayMode",
        ):
            self.assertNotIn(rejected, self.app)

    def test_presentation_modules_load_before_host_and_never_own_media_transport(self):
        scene_index = self.index.index('src="/presentation-scene.js"')
        renderer_index = self.index.index('src="/presentation-renderer.js"')
        app_index = self.index.index('src="/app.js"')
        self.assertLess(scene_index, renderer_index)
        self.assertLess(renderer_index, app_index)
        presentation_only = "\n".join((self.scene, self.renderer, self.controller))
        for forbidden in (
            "BroadcastChannel",
            "localStorage",
            "playbackRate",
            "predictedTime",
            "driftCorrection",
            'createElement("video")',
            'createElement("audio")',
            "/api/player/",
            "EventSource",
        ):
            self.assertNotIn(forbidden, presentation_only)

    def test_host_presentation_block_has_no_follower_transport_or_media_constructor(self):
        start = self.app.index("function presentationSceneApi")
        end = self.app.index("function renderPlayerFullscreenButton", start)
        block = self.app[start:end]
        for forbidden in (
            "BroadcastChannel",
            "localStorage",
            'createElement("video")',
            'createElement("audio")',
            "playbackRate",
            "predictedTime",
            "open_stage_window",
        ):
            self.assertNotIn(forbidden, block)
        self.assertIn('playbackAuthority !== "host"', block)
        self.assertIn('mediaRendererOwner !== "host"', block)

    def test_i18n_has_controller_and_presentation_keys_in_all_languages(self):
        def reject_duplicate_keys(pairs):
            result = {}
            for key, value in pairs:
                if key in result:
                    raise ValueError(f"duplicate i18n key: {key}")
                result[key] = value
            return result

        catalog = json.loads(
            (self.static / "i18n.json").read_text(encoding="utf-8"),
            object_pairs_hook=reject_duplicate_keys,
        )
        required = {
            "document.controllerTitle",
            "display.presentationActive",
            "display.presentationActivating",
            "display.presentationRecovering",
            "display.presentationNoExternalDisplay",
            "display.presentationDisconnected",
            "controller.title",
            "controller.statusActive",
            "controller.play",
            "controller.pause",
            "controller.backTen",
            "controller.forwardTen",
            "controller.next",
            "controller.volume",
            "controller.exit",
            "controller.tauriRequired",
        }
        for language, translations in catalog["languages"].items():
            self.assertEqual(required - set(translations), set(), language)
        rejected = {
            "display.stageOutput",
            "display.stageOutputOff",
            "display.stageOutputConnecting",
            "display.stageOutputConnected",
            "display.stageOutputDetected",
            "display.stageOutputConnectedSecondary",
            "display.openStage",
            "display.closeStage",
            "display.stageOpenFailed",
            "display.stageTargetSelected",
            "display.stageDisconnected",
            "display.stageOutputWindowed",
            "display.stageOutputConnectedWindowed",
            "display.windowMode",
            "display.windowModeDetail",
            "display.stageWindowSelected",
            "display.windowOutputOn",
            "display.stageFellBackWindow",
            "display.wirelessCast",
            "display.wirelessCastLater",
            "display.comingSoon",
        }
        for language, translations in catalog["languages"].items():
            self.assertEqual(rejected & set(translations), set(), language)
        language_key_sets = {
            language: set(translations)
            for language, translations in catalog["languages"].items()
        }
        reference_language, reference_keys = next(iter(language_key_sets.items()))
        for language, keys in language_key_sets.items():
            self.assertEqual(keys, reference_keys, f"{language} differs from {reference_language}")

    def test_controller_and_presentation_assets_are_in_the_generic_static_bundle(self):
        assets = (
            "controller.html",
            "controller.js",
            "controller.css",
            "presentation-scene.js",
            "presentation-renderer.js",
        )
        for asset in assets:
            self.assertTrue((self.static / asset).is_file(), asset)
        self.assertFalse((self.static / "stage.html").exists())
        server_source = (ROOT / "bilikara" / "server.py").read_text(encoding="utf-8")
        static_handler = server_source[
            server_source.index("    def _serve_static") : server_source.index(
                "    def _serve_media", server_source.index("    def _serve_static")
            )
        ]
        self.assertIn("relative = route.lstrip", static_handler)
        self.assertIn("not static_path.exists()", static_handler)
        bundle_source = (ROOT / "build_bundle.py").read_text(encoding="utf-8")
        self.assertIn("static_arg =", bundle_source)
        self.assertIn("ROOT_DIR / 'static'", bundle_source)


if __name__ == "__main__":
    unittest.main()
